import { FopData, CreateFopFormState } from "../types/fop";

export const INITIAL_FOPS: FopData[] = [
  {
    id: 1,
    kod: "КД-10492",
    vezeteknev: "Коваленко",
    keresztnev: "Олександр",
    apai_nev: "Іванович",
    nem: "Чоловік",
    fop_kod: "ФОП-10492",
    fop_kezdete_datum: "2020-01-15",
    nakaz_szam: "1",
    munkas_szam: "1",
    munkasok: [
      {
        id: 101,
        kod: "КД-80145",
        vezeteknev: "Шевченко",
        keresztnev: "Катерина",
        apai_nev: "Петрівна",
        nem: "Жінка",
        foallas: true,
        teljes_munkaido: true,
        foglalkozas_megnevezes: "Головний бухгалтер",
        fizetes: 350000,
      },
      {
        id: 102,
        kod: "КД-80219",
        vezeteknev: "Кравченко",
        keresztnev: "Василь",
        apai_nev: "Леонідович",
        nem: "Чоловік",
        foallas: false,
        teljes_munkaido: false,
        foglalkozas_megnevezes: "IT-консультант",
        fizetes: 185000,
      },
      {
        id: 103,
        kod: "КД-80362",
        vezeteknev: "Ткаченко",
        keresztnev: "Олена",
        apai_nev: "Дмитрівна",
        nem: "Жінка",
        foallas: true,
        teljes_munkaido: true,
        foglalkozas_megnevezes: "Офіс-адміністратор",
        fizetes: 260000,
      },
    ],
  },
  {
    id: 2,
    kod: "КД-20831",
    vezeteknev: "Мельник",
    keresztnev: "Михайло",
    apai_nev: "Степанович",
    nem: "Чоловік",
    fop_kod: "ФОП-20831",
    fop_kezdete_datum: "2021-06-01",
    nakaz_szam: "1",
    munkas_szam: "1",
    munkasok: [
      {
        id: 201,
        kod: "КД-91504",
        vezeteknev: "Бондаренко",
        keresztnev: "Андрій",
        apai_nev: "Сергійович",
        nem: "Чоловік",
        foallas: true,
        teljes_munkaido: true,
        foglalkozas_megnevezes: "Менеджер з логістики",
        fizetes: 410000,
      },
      {
        id: 202,
        kod: "КД-91687",
        vezeteknev: "Бойко",
        keresztnev: "Оксана",
        apai_nev: "Володимирівна",
        nem: "Жінка",
        foallas: true,
        teljes_munkaido: false,
        foglalkozas_megnevezes: "Завідувач складу",
        fizetes: 220000,
      },
    ],
  },
  {
    id: 3,
    kod: "КД-30114",
    vezeteknev: "Сидоренко",
    keresztnev: "Валерій",
    apai_nev: "Анатолійович",
    nem: "Чоловік",
    fop_kod: "ФОП-30114",
    fop_kezdete_datum: "2023-03-10",
    nakaz_szam: "1",
    munkas_szam: "1",
    munkasok: [],
  },
];

export const INITIAL_FORM_STATE: CreateFopFormState = {
  vezeteknev: "",
  keresztnev: "",
  apai_nev: "",
  kod: "",
  szuletesi_datum: "",
  nem: "",

  fop_kod: "",
  fop_kezdete_datum: "",

  iranyitoszam: "",
  megye: "",
  jaras: "",
  kozseg: "",
  utca: "",
  hazszam: "",
  epulet: "",
  lakas_szoba: "",
  orszag: "Україна",

  okmany_tipus: 0,
  szeria: "",
  okmanyszam: "",
  kiallitott_hatosag: "",
  hatosagi_kod: "",
  kiallitasi_datum: "",
  lejarati_datum: "",
};
